services:
  blog_service:
    image: june050312/blog:latest
    container_name: blog_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://blog_db:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
    ports:
      - "8081:8080"
    depends_on:
      - blog_db
    networks:
      - blog-network

  blog_db:
    image: mariadb:latest
    container_name: blog_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - blog_data:/var/lib/mysql
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  blog_data: